[esp-wifi]
heap_size = 112640 # use 110k by default
rx_queue_size = 15
tx_queue_size = 3
static_rx_buf_num = 10
dynamic_rx_buf_num = 18
ampdu_rx_enable = 0
ampdu_tx_enable = 0
rx_ba_win = 16
max_burst_size = 6